default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] || "localhost" %>
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: tg_rails_crm_development

test:
  <<: *default
  database: tg_rails_crm_test
